### ISSUE TITLE
My two cents

### ISSUE THREAD

**Issue by christiankaye** [lectrode/xs-update-manjaro#33]
Thank you.
I have installed "xs-update-manjaro" on at least three machines without any problems at all.
Here is my script.txt if you want it.

[xs-lectrode-install.txt](https://github.com/lectrode/xs-update-manjaro/files/5375607/xs-lectrode-install.txt)

**Comment by lectrode** [comment]
thank you for the script. historically i've been hesitant to provide an automated solution for installing this update script, as i'd prefer that people only install this if they are willing to read instructions, that way they know exactly what and where the pieces are, as well as the potential risks involved.

however, i'll consider adding a script to facilitate that to the readme, that way they'll still have to read that before they find it.
